# Site settings
title: stoyanovd notes
email: stoyanovd@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  notes about everything
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stoyanovd.github.io/" # the base hostname & protocol for your site
github_username:  stoyanovd
vk_username: stoyanovd

# Build settings
markdown: kramdown
sass:
	sass_dir: _sass



# not all will be run on GitHub Pages
gems:

# emoticons
  - jemoji
  
  
# @mentions link the mention to the user's GitHub profile. However, they don't notify the user.
  - jekyll-mentions
  
  
#  ---
#  redirect_from: "/foo"
#  ---
  - jekyll-redirect-from


# Make sitemap for Google and another
# GitHub: https://help.github.com/articles/sitemaps-for-github-pages/
# Google https://support.google.com/webmasters/answer/156184?hl=en
  - jekyll-sitemap
