# Site settings
title: stoyanovd notes
email: stoyanovd@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  stoyanovd notes about everything
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stoyanovd.github.io/" # the base hostname & protocol for your site
github_username:  stoyanovd
vk_username: stoyanovd

# Build settings
markdown: kramdown


# not all will be run on GitHub Pages
gems:
  # emoticons
  - jemoji
